#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

[[ -s ~/.zprofile ]] && source ~/.zprofile

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

bindkey -v
export EDITOR=vim

bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward


# Ensures that $terminfo values are valid and updates editor information when
# the keymap changes.
function zle-keymap-select zle-line-init zle-line-finish {
  # The terminal must be in application mode when ZLE is active for $terminfo
  # values to be valid.
  if (( ${+terminfo[smkx]} )); then
printf '%s' ${terminfo[smkx]}
  fi
if (( ${+terminfo[rmkx]} )); then
printf '%s' ${terminfo[rmkx]}
  fi

zle reset-prompt
  zle -R
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select
zle -N edit-command-line

ZLE_REMOVE_SUFFIX_CHARS=""

bindkey -v

# allow v to edit the command line (standard behaviour)
autoload -Uz edit-command-line
bindkey -M vicmd 'v' edit-command-line

# if mode indicator wasn't setup by theme, define default
if [[ "$MODE_INDICATOR" == "" ]]; then
MODE_INDICATOR="%{$fg_bold[red]%}<%{$fg[red]%}<<%{$reset_color%}"
fi

function vi_mode_prompt_info() {
  echo "${${KEYMAP/vicmd/$MODE_INDICATOR}/(main|viins)/}"
}

# define right prompt, if it wasn't defined by a theme
if [[ "$RPS1" == "" && "$RPROMPT" == "" ]]; then
RPS1='$(vi_mode_prompt_info)'
fi

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

alias ls='ls -p'
alias l='ls'
alias ll='ls -l'

alias clearpyc='find . -name "*.pyc" | xargs rm'
alias cleardirs='find . -type d | xargs rmdir 2>/dev/null'
alias cpd='clearpyc && cleardirs'

alias grep='grep --color=always'

alias json='python -m json.tool'

alias git=hub
alias gc="git commit"
alias gpl="git pull"
alias gps="git push"

alias vim=nvim

alias k=kubectl

[[ -s "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

eval "$(direnv hook zsh)"

export NVM_DIR="/usr/local/opt/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
eval "$(direnv hook zsh)"

export PATH="$HOME/.poetry/bin:$PATH"
export PATH="${HOME}/.local/bin:${PATH}"
source "/Users/robgolding/src/zapier/shell-tools/scripts.sh"

eval "$(scmpuff init -s)"
